# Generated by Django 3.0.4 on 2020-03-29 06:52

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254, unique=True)),
                ('describe', models.TextField(default='')),
                ('identification', models.CharField(max_length=254, unique=True)),
            ],
            options={
                'db_table': 'jurisdiction',
            },
        ),
    ]
