# Generated by Django 3.0.4 on 2020-03-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JurisdictionManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurisdiction',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='JurisdictionManage.Jurisdiction'),
        ),
    ]
