# Generated by Django 3.0.4 on 2020-03-31 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JurisdictionManage', '0002_jurisdiction_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jurisdiction',
            name='parent',
        ),
    ]
