# Generated by Django 3.0.4 on 2020-03-29 06:52

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('JurisdictionManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('describe', models.TextField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('jurisdiction', models.ManyToManyField(related_name='d_jurisdictions', to='JurisdictionManage.Jurisdiction')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='DeptManage.Department')),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
