# Generated by Django 3.0.4 on 2020-03-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginManage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
